AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Demo Lambda
Resources:
  LambdaCD:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      Description: 'Lambda function for Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::551638562717:role/LambdaDeploymentStack-CDDemoLambdaRole-1QN6X8EUGQC8W'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-1

Outputs:

   LambdaCDApi:
      Description: "API Gateway endpoint URL for getAZs function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getazs/"

    LambdaCD:
      Description: "Demo Lambda Function ARN"
      Value: !GetAtt LambdaCD.Arn

    LambdaCDFunctionIamRole:
      Description: "Implicit IAM Role created for LambdaCD function"
      Value: !GetAtt HelloWorldFunctionRole.Arn
