AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A simple backend (read/write to DynamoDB) with a RESTful API endpoint using
  Amazon API Gateway.
Resources:
  DynamoDBMicroService:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: >-
        A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      MemorySize: 256
      Timeout: 10
      Role: 'arn:aws:iam::551638562717:role/service-role/MicroServiceRole'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /DynamoDBMicroService
            Method: ANY
      Tags:
        'lambda-console:blueprint': microservice-http-endpoint-python3
